### PR TITLE
Update MqttNetworkChannel.cs

### PR DESCRIPTION
**Pull request by GioviQ**
Explanation request

### CODE REVIEW

**Comment by ppatierno** [comment]
The current full .Net Framework implementation uses the Certification Authority certificates installed on the PC where application is executing.
For .Net Micro Framework it isn't possible so the X509 certificate array is mandatory.
Of course, it could be possible to allow the double choice for .Net Framework version (using CA certificate installed on the PC or X509 certificate array).

Paolo.

**Comment by GioviQ** [comment]
In questo articolo http://www.tinyclr.it/mqtt-su-ssltls-con-la-libreria-m2mqtt-ed-il-broker-mosquitto.aspx usi questo costruttore: new MqttClient("ppatierno-PC",
              MqttClient.MQTT_BROKER_DEFAULT_SSL_PORT,
              true,
              new X509Certificate(Resources.m2mqtt_ca))
Il certificato è quello della della CA, ma in base a https://msdn.microsoft.com/it-it/library/ms145061(v=vs.110).aspx mi aspetterei di trovare un certificato creato apposta per il client.
In definitiva testato assieme a GnatMQ non riesco ad ottenere lato server un certificato restituito alla RemoteCertificateValidationCallback. C'è qualcosa che non mi torna...

**Comment by ppatierno** [comment]
The MqttClient constructor has no relation (in terms of parameters order) with AuthenticateAsClient method overload.
The .Net Framework version uses the overload you linked where the parameter related to the X509 client certificate is always null (M2Mqtt doesn't support SSL/TLS client authentication).
Of course in my old article I used the MqttClient constructor overload where the CA certificate is useless because the PC version uses the CA certificate installed on PC itself. The above constructor is good for .Net Micro Framework but it still works for PC version (the uselss parameter isn't used as I said).

Paolo

PS : please, can you translate in english what you wrote. I prefer that all people could read issues for this library. Thanks.

**Comment by GioviQ** [comment]
So in conclusion M2Mqtt doesn't support SSL/TLS client authentication and for someone not using .Net Micro Framework the uselss parameter is misleading. It would be better to support client authentication.
Thank you

**Comment by ppatierno** [comment]
About the parameter caCert the documentation is clear : it's the CA certificate not client certificate.
Support client authentication doesn't have big application on real scenarios because handling certificates with related expire dates on a lot of devices it's very difficult. 
The client authentication is always enabled with API keys, tokens and so on at application layer.

M2Mqtt won't support client authentication in the near/middle future.

Paolo.

**Pull request closed without merging**
