### PR TITLE
Added Xamarin Support for Android and iOS

### PR DESCRIPTION
**Pull request by reicheltp**
I added Xamarin Support for Android and iOS. No code changes were required. Just compiled against an other target platform.

Best regards,
Paul

### CODE REVIEW

**Comment by pjduerden** [comment]
Hi Paul

Is there any chance this branch will be brought up to date with the latest from ppatierno:master.

I'm particularly interested in the following Client constructor.

public MqttClient(string brokerHostName, int brokerPort, bool secure, X509Certificate caCert, X509Certificate clientCert, MqttSslProtocols sslProtocol)

Regards

Peter

**Comment by reicheltp** [comment]
If I got time this week, I will take a look on the changes and update my branch.

**Comment by MKahmen** [comment]
you can just use the Patiernos Mono-Solution. works well in Xamarin without changes...

https://github.com/ppatierno/m2mqtt/blob/master/M2Mqtt/M2Mqtt.Mono.csproj

Would be cool, if he would add it to nuget...

**Comment by adrienjeanjean** [comment]
@MKahmen Do you mean Patiernos' Mono Solution can be used in a PCL Project which in turn is used in a Xamarin.iOS & Xamarin.Android project?

**Comment by MKahmen** [comment]
@adrienjeanjean indeed. Use it in xamarin since a while now. Works great.

**Comment by adrienjeanjean** [comment]
@MKahmen Then I must be doing something wrong. I can't seem to reference the M2Mqtt.Mono project from my Core PCL. It says Incompatible target framework: .NETFramework,Version=4.0). My PCL has Profile78. I've attached a zip of my attempt at setting up the solution.

[MqttProofOfConcept.zip](https://github.com/ppatierno/m2mqtt/files/146974/MqttProofOfConcept.zip)

**Comment by MKahmen** [comment]
Well that's true. You have to reference it in each project. Then just build an interface in your PCL and use the DependencyService. It just takes you a few minutes but unfortunately it seems to be the only solution right now.
A Xanarin Plugin for Xamarin.Forms would be great.

**Comment by adrienjeanjean** [comment]
@MKahmen Sorry for being so thick, but I still don't understand what I should do with the M2Mqtt.Mono project in my case. What do you mean with "you have to reference it in each project"? I can't reference it from any of my projects. 

Thanks for your patience and replying so promptly! :)

**Comment by MKahmen** [comment]
[M2Mqtt.Mono.dll.zip](https://github.com/ppatierno/m2mqtt/files/147094/M2Mqtt.Mono.dll.zip)

Try using this as a reference in your Xamarin.iOS & Xamarin.Android projects. not in PCL!

It's build against Mono / .NET 4.5 and works great for me.

**Comment by adrienjeanjean** [comment]
I added the dll to my mobile projects and that works. Thanks @MKahmen

**Comment by sdippl** [comment]
@MKahmen @adrienjeanjean is anyone of you using this in a background service to receive messages when the actual app is not running or just while the app is running in foreground?

**Comment by MKahmen** [comment]
@sdippl I used an android service once (in java). Since this lib is basically the same, take a look at this post, it's pretty good:
https://developer.zebra.com/docs/DOC-2315

Have fun

**Comment by sdippl** [comment]
Thanks, @MKahmen! I'll check it out

**Comment by adrienjeanjean** [comment]
@sdippl no I haven't yet, but plan to for both Android & iOS. @MKahmen thanks for the link!

**Comment by WarBorg** [comment]
any news on the merge of this branch? like @MKahmen said a plugin for Xamarin Forms would be super, as Xamarin has now become a big player in the mobile world there should be something like this available

**Comment by scolestock** [comment]
+1 to getting this branch integrated - thanks!

**Comment by rmoquin** [comment]
I would love to see it integrated as well!

**Comment by MKahmen** [comment]
hey guys, did anyone of you manage to get TLS 1.2 running? I know that its not natively supported by Mono and the (Xamarin-)Team is working on it but maybe someone already has a solution / experience?

**Pull request closed without merging**
